apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${artifact_name}
  namespace: elm-integration
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: elm
  template:
    metadata:
      labels:
        app: elm
      name: ${artifact_name}
    spec:
      containers:
        - command:
          - /bin/sh
          - '-c'
          - 'java -Dspring.profiles.active=np -jar app.jar'
          envFrom:
            - configMapRef:
                name: ${artifact_name}-config
          image: us-east1-docker.pkg.dev/np-sc-distribution/gcf-artifacts/com/homedepot/supplychain/${artifact_name}/np:${image_version}
          imagePullPolicy: Always
          name: elm
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '1'
              memory: 1Gi
              ephemeral-storage: 1Gi
            limits:
              cpu: '1'
              memory: 1Gi
              ephemeral-storage: 1Gi

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5

      serviceAccountName: elm-integration
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${artifact_name}-auto-scale
  namespace: elm-integration
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${artifact_name}
  minReplicas: ${#toInt(min_pods)}
  maxReplicas: ${#toInt(max_pods)}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
