apiVersion: v1
kind: Service
metadata:
  labels:
    app: elm
  name: ${artifact_name}
  namespace: elm-integration
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: elm
  type: ClusterIP